fix: Ignore NRF URI containing a specific IP on registration
omec-project/udr pull request #26
Opened 2023-11-27 20:22 UTC by ghislainbourgeois

This ignores the NRF URI received from the NRF on registration, as the NRF will return its IP, which is subject to change. This is similar to what is done on the AMF.

2023-12-10 00:48 UTC, gab-arrobo commented
ok to test

2023-12-10 13:30 UTC, gab-arrobo commented on factory/config.example.yaml
How is this file used? I do not see being called from anywhere. If this file is required, the "License verification" fails because this file does not have License/Copyright header.

2023-12-11 00:47 UTC, gab-arrobo commented
@ghislainbourgeois please rebase your PR. Thanks!

2023-12-11 14:02 UTC, ghislainbourgeois commented on factory/config.example.yaml
It is used by the test I added, it needs to read a configuration file to initialize before the test. I added the license and copyright.

2023-12-11 14:02 UTC, ghislainbourgeois commented
> @ghislainbourgeois please rebase your PR. Thanks!

@gab-arrobo I just rebased and added license and copyright to the file that was missing it. Thanks!

2023-12-12 01:12 UTC, gab-arrobo requested changes

2023-12-12 01:12 UTC, gab-arrobo commented on factory/config.example.yaml
> +  sbi: # Service-based interface information
As per its abbreviation in 23.501:
```suggestion
  sbi: # Service Based Interface
```

2023-12-12 22:04 UTC, gab-arrobo commented
ok to test

2023-12-12 23:15 UTC, gab-arrobo approved these changes
+1

2023-12-12 23:16 UTC, merged